[package]
name = "monitor-rust"
version = "0.1.0"
authors = ["Gyuho Lee <gyuho@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
